# Generated by Django 3.1.4 on 2020-12-10 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_oznamy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UradnaTabula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('title1', models.CharField(blank=True, max_length=200)),
                ('file1', models.FileField(blank=True, upload_to='files/')),
                ('title2', models.CharField(blank=True, max_length=200)),
                ('file2', models.FileField(blank=True, upload_to='files/')),
                ('title3', models.CharField(blank=True, max_length=200)),
                ('file3', models.FileField(blank=True, upload_to='files/')),
                ('title4', models.CharField(blank=True, max_length=200)),
                ('file4', models.FileField(blank=True, upload_to='files/')),
                ('title5', models.CharField(blank=True, max_length=200)),
                ('file5', models.FileField(blank=True, upload_to='files/')),
            ],
            options={
                'verbose_name_plural': 'Uradna Tabula',
            },
        ),
        migrations.AlterModelOptions(
            name='oznamy',
            options={'verbose_name_plural': 'oznamy'},
        ),
        migrations.AlterField(
            model_name='oznamy',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
