# Generated by Django 3.1.4 on 2020-12-12 16:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201210_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odpad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.CharField(choices=[('Január', 'Januar'), ('Február', 'Februar'), ('Marec', 'Marec'), ('Apríl', 'April'), ('Máj', 'Maj'), ('Jún', 'Jun'), ('Júl', 'Jul'), ('August', 'August'), ('September', 'September'), ('Október', 'Oktober'), ('November', 'November'), ('December', 'December')], default='', max_length=200)),
                ('description', models.CharField(choices=[('Komunálny odpad', 'Komunalny'), ('Zmiešané plasty, PET fľaše', 'Plasty'), ('Sklo', 'Sklo'), ('Papier', 'Papier'), ('Elektro, VKM, Kovové obaly', 'Elektro'), ('Nebezpečný odpad', 'Nebezpecny')], default='', max_length=250)),
                ('week_day', models.CharField(choices=[('Podnelok', 'Pondelok'), ('Utorok', 'Utorok'), ('Streda', 'Streda'), ('Štvrtok', 'Stvrtok'), ('Piatok', 'Piatok'), ('Sobota', 'Sobota'), ('Nedeľa', 'Nedela')], default='', max_length=160)),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18)),
            ],
        ),
    ]
