# Generated by Django 3.1.4 on 2020-12-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_odpad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odpad',
            options={'verbose_name_plural': 'Odpady'},
        ),
    ]
