# Generated by Django 3.1.4 on 2020-12-27 12:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_aktuality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vzn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/vzn/')),
            ],
            options={
                'verbose_name_plural': 'vzn',
            },
        ),
        migrations.AlterField(
            model_name='oznamy',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
