# Generated by Django 3.1.4 on 2020-12-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201227_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturyRok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Faktury rok',
            },
        ),
        migrations.CreateModel(
            name='FakturyFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('faktura', models.FileField(upload_to='files/faktury')),
                ('rok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktury', to='pages.fakturyrok')),
            ],
            options={
                'verbose_name_plural': 'Faktury subory',
            },
        ),
    ]
