# Generated by Django 3.1.4 on 2020-12-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_fakturyfiles_fakturyrok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZapisniceObdobie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obdobie', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Zapisnice obdobie',
            },
        ),
        migrations.CreateModel(
            name='ZapisniceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Zápisnica', 'Zapisnica'), ('Uznesenie', 'Uznesenie')], default='', max_length=160)),
                ('zapisnica', models.FileField(blank=True, upload_to='files/zapisnice')),
                ('uznesenie', models.FileField(blank=True, upload_to='files/uznesenia')),
                ('obdobie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisnice', to='pages.zapisniceobdobie')),
            ],
            options={
                'verbose_name_plural': 'Zapisnice subory',
            },
        ),
    ]
