# Generated by Django 3.1.4 on 2020-12-30 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_zapisnicefiles_zapisniceobdobie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapisnicefiles',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
