# Generated by Django 3.1.4 on 2020-12-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_zapisnicefiles_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZmluvyRok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Zmluvy rok',
            },
        ),
        migrations.AlterModelOptions(
            name='zapisnicefiles',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Zapisnice subory'},
        ),
        migrations.CreateModel(
            name='ZmluvyFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('zmluva', models.FileField(upload_to='files/zmluvy')),
                ('rok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zmluvy', to='pages.zmluvyrok')),
            ],
            options={
                'verbose_name_plural': 'Zmluvy subory',
            },
        ),
    ]
