# Generated by Django 3.1.4 on 2020-12-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201230_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='zmluvyfiles',
            name='cislo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
