# Generated by Django 3.1.4 on 2021-01-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_zmluvyfiles_cislo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zmluvyfiles',
            name='zmluvne_strany',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
